import { Inter } from "next/font/google";
import "./globals.css";
import { library } from '@fortawesome/fontawesome-svg-core';
import { far } from '@fortawesome/free-regular-svg-icons';  // Import the regular icons
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css'; // Import the CSS

// Prevent FontAwesome from adding its CSS automatically
config.autoAddCss = false;

// Add the regular icons to the library
library.add(far);



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cyparta Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
